# Generated by Django 4.1.7 on 2023-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='u_username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
