# Generated by Django 4.1.7 on 2023-05-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0005_userprofile_u_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='u_username',
        ),
    ]
